# version: '3'
# services:
#     autocomplete:
#         container_name: autocomplete
#         build: .
#         ports:
#             - "3001:3001"
#         depends_on:
#             - elastic
#         environment:
#             # - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
#             # - MONGO_DB_URI=mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/book?replicaSet=spike
    
#     kibana01:
#         container_name: kibana01
#         image: docker.elastic.co/kibana/kibana:7.7.1
#         environment:
#             - SERVER_NAME: "kibana"
#             - ELASTICSEARCH_HOSTS: http://elastic01:9200,
#             # - ELASTICSEARCH_USERNAME=elastic
#             # - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
#         ports:
#             - "5601:5601"
#         networks: ['elastic']
    
#     elastic01:
#         image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
#         # ports: "9200:9200"
#         environment:
#             - node.name=elastic
#             - cluster.name=es-docker-cluster
#             - discovery.seed_host=elastic
#             - discovery.type=single-node
#             - cluster.initial_master_nodes=elastic
#             - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#             # - xpack.security.enabled=$ELASTIC_SECURITY
    
#         ulimits:
#             memlock:
#                 soft: -1
#                 hard: -1
#             # volumes:
#             #     - esdata1:/usr/share/elasticsearch/data
#             networks:
#                 - elastic
#             ports:
#                 - "9200:9200"

# volumes:
#     esdata1:
#         driver: local

# networks:
#     elastic:
#         driver: bridge


---
version: '3'
services:

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - esdata1:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:7.7.1
        environment:
            ELASTICSEARCH_URL: http://elasticsearch:9200
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            # - ELASTICSEARCH_USERNAME=elastic
            # - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
        ports: ['5601:5601']
        networks: ['elastic']
        links: ['elasticsearch']
        depends_on: ['elasticsearch']
volumes:
    esdata1:
        driver: local

networks:
    elastic:
        driver: bridge