---
version: '3.0'
services:
    autocomplete:
        container_name: autocomplete
        build: .
        # command: sh ./start.sh
        restart: on-failure
        ports:
            - "3001:3001"
        depends_on:
            - elasticsearch
        links:
            - elasticsearch
        # environment:
            # - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
            # - MONGO_DB_URI=mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/book?replicaSet=spike
        networks:
            - elastic

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        ports:
          - "9200:9200"
          - "9300:9300"
        # configs:
        #   - source: elastic_config
        #     target: /usr/share/elasticsearch/config/elasticsearch.yml
        environment:
          ES_JAVA_OPTS: "-Xmx256m -Xms256m"
          ELASTIC_PASSWORD: changeme
          # Use single node discovery in order to disable production mode and avoid bootstrap checks
          # see https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
          discovery.type: single-node
        healthcheck:
            test: ["CMD", "curl", "-f", "http://0.0.0.0:9200"]
            interval: 30s
            timeout: 10s
            retries: 5
        networks:
          - elastic

    kibana:
        image: docker.elastic.co/kibana/kibana:7.8.0
        ports:
          - "5601:5601"
        # configs:
        #   - source: kibana_config
        #     target: /usr/share/kibana/config/kibana.yml
        networks:
          - elastic
        # deploy:
        #   mode: replicated
        #   replicas: 1
    
    logstash:
        image: docker.elastic.co/logstash/logstash:7.8.0
        # secrets:
        #     - source: ./logstash.conf
        #       target: /usr/share/logstash/pipeline/logstash.conf
        ports:
            - "5000:5000"
            - "9600:9600"
        # configs:
        #     - source: logstash_config
        #       target: /usr/share/logstash/config/logstash.yml
        #     - source: logstash_pipeline
        #       target: /usr/share/logstash/pipeline/logstash.conf
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
        networks:
            - elastic
        # volumes:
        #     - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
        # volumes:
        #     - type: bind
        #     source: ./logstash.conf
        #         target: /usr/share/logstash
        healthcheck:
            test: bin/logstash -t
            interval: 60s
            timeout: 50s
            retries: 5
        # deploy:
        #     mode: replicated
        #     replicas: 1

# configs:
#     elastic_config:
#         file: ./elasticsearch.yml
#     logstash_config:
#         file: ./logstash.yml
#     logstash_pipeline:
#         file: ./logstash.conf
#     kibana_config:
#         file: ./kibana.yml

volumes:
    esdata1:
        driver: local

networks:
    elastic:
        driver: bridge